"""Add workouts table with foreign key to users

Revision ID: ab52a8c0fcb8
Revises: b5fa6c4653db
Create Date: 2026-01-04 14:21:24.099505

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab52a8c0fcb8"
down_revision: str | Sequence[str] | None = "b5fa6c4653db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workouts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "exercise_type",
            sa.Enum("PUSH_UP", "JUMP_ROPE", name="exercise_type_enum"),
            nullable=False,
        ),
        sa.Column("reps_count", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("calories_burned", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workouts_exercise_type"), "workouts", ["exercise_type"], unique=False)
    op.create_index(op.f("ix_workouts_user_id"), "workouts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workouts_user_id"), table_name="workouts")
    op.drop_index(op.f("ix_workouts_exercise_type"), table_name="workouts")
    op.drop_table("workouts")
    # ### end Alembic commands ###
